// app/terms-of-service/page.tsx
import Layout from '../../components/Layout';

export default function TermsOfServicePage() {
  return (
    <Layout>
      <div className="prose prose-invert max-w-none">
        <h2>Terms of Service</h2>
        <p>Welcome to AI Oracle. By using our service, you agree to these Terms of Service. Please read them carefully.</p>

        <h3>Access to the Service</h3>
        <p>The AI Oracle is an AI-powered tool that generates rituals and ceremonies. You are responsible for ensuring your use of this tool complies with all applicable laws and regulations. You must be at least 18 years old to use our paid services.</p>

        <h3>Intellectual Property</h3>
        <p>The content generated by our AI is for your personal use. You may use the generated content in your own spiritual practice. However, you may not sell or redistribute the content without our express written permission.</p>

        <h3>Disclaimer of Warranties</h3>
        <p>The AI Oracle is provided &quot;as is&quot; without any warranties. We do not guarantee that the content generated will be accurate, complete, or suitable for your specific needs.</p>

        <h3>Limitation of Liability</h3>
        <p>We are not liable for any damages or losses related to your use of this service.</p>

        <h3>Changes to the Terms</h3>
        <p>We may modify these terms at any time. By continuing to use the service after changes are made, you agree to be bound by the updated terms.</p>
      </div>
    </Layout>
  );
}